### PR TITLE
Implement objects classes

### PR DESCRIPTION
**Pull request by MikeJollie2707**
- Change prerequisite array in `Course` to contains course ID instead of `Course`. Also change from array to set.
  - Course ID: This prevent `insertPrereq()` from being used to add a course from outside the uni catalog. It's still possible to fake up a non-existing course ID, but it's much easier to detect if it's fake by using the uni's catalog.
  - Set: We care more about uniqueness than ordering, so set is a more suitable choice.
- Implement prerequisite cycle check when adding and editing a new course to the university.
  - Editing a course is not tested extensively.
- Implement `Student` class.
- Add time check in `ScheduleEntry` constructor.

If approved:
- The PR is squashed and merged.
- Branch `impl_objects` is deleted.

### CODE REVIEW

**Review by JanelleKwofie — APPROVED** [review]
If you take a look at my code for schedule entry, I made a Tuple class so time could be a Tuple (Java does not have Tuples you have to create it)

**Comment by MikeJollie2707** [comment]
> If you take a look at my code for schedule entry, I made a Tuple class so time could be a Tuple (Java does not have Tuples you have to create it)

Sure I'll copy that implementation over and add some getters.

**Review by AntioniRavioli — COMMENTED** [review]
I think it looks good, I might add my Branch later tonight and ask for some reviews as well.

**Comment by MikeJollie2707** [comment]
Since you merged the branch already, I'll cherry pick my new commit to a new branch. `impl_objects` will be deleted soon.

**Pull request merged**
